services:
  frontend:
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/app/src
    command: "npm run dev"
    ports:
      - "3000:3000"
    environment:
      - PORT="3000"
      - VITE_API_URL=http://localhost:8080
